version: "2"
services:
    nginx_firstapp:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./media:/media
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - flask

    flask:
        build: .
        hostname: "${PROJECT_NAME}_flask"
        container_name: "${PROJECT_NAME}_flask"
        tty: true
        volumes:
            - ./src:/src
            - ./media:/media
        expose:
            - "5000"
        links:
            - postgresql:postgresql
        depends_on:
            - postgresql
        environment:
            - C_FORCE_ROOT=true
            - APP_CONFIG_FILE=/src/config/local.py
            - FLASK_APP=${PROJECT_NAME}
            - FLASK_DEBUG=1

    postgresql:
        image: postgres:11
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"

    data:
        image: postgres:11
        hostname: "${PROJECT_NAME}_postgres_data"
        container_name: "${PROJECT_NAME}_postgres_data"
        volumes:
            - /var/lib/postgresql/data
        command: "true"

